swagger: '2.0'
info:
  version: 1.0-SNAPSHOT
  title: USM-administration
basePath: /rest
paths:
  /profile/userPassword:
    put:
      description: Update an existing password
      operationId: updatePassword
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
         -
          description: the JWT token authenticating the service requester
          name: authorisation
          in: header
          required: true
          type: string
         -
          description: The user password to be updated
          name: userPassword
          required: true
          in: body
          schema:
            $ref: '#/definitions/UserPassword'
      responses:
        '200':
          description: users responses
        '400':
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  UserPassword:
    required:
      - userName
      - newPassword
      - currentPassword
    properties:
      userName:
        type: string
        description: The userName of the current user
      newPassword:
        type: string
        description: The new password of the current user
      currentPassword:
        type: string
        description: the new current password of the current user
  errorModel:
    required:
        - statusCode
        - message
    properties:
      statusCode:
        type: integer
        format: int32
      message:
        type: string